### ISSUE TITLE
On the Contact page: Need a contact form that sends an email to kristi@uxlocal.com

### ISSUE THREAD

**Issue by kwritenow** [kwritenow/kristileach.com#22]

**Comment by evz** [comment]
Since we're building a site that we're hosing on github pages, this is slightly tricky (but not impossible). We could:

* Use a third party service to handle the email for us. The caveat here is that when someone submits the form, they'll be redirected to that site, have to fill out a recaptcha, and then get redirected back to your site.
* Instead of a "contact" form have it be a "signup for my newsletter" form and just embed a mailchimp form. I know this is not what you want but I'm just spitballing here.
* Build the site in a way that isn't hosted on github pages and actually has a server side. There are many, many benefits to this besides being able to have a working contact form. This can be had for free (by using AWS's free tier) for a year and then after that it'll be like $5 / month. This will get you your own cloud server, too.

We should probably figure out a direction here soon-ish because we'll need to decide whether the tech I'm using is appropriate.

**Comment by evz** [comment]
Oh, as an explanatory note, the reason why we can't just stick a form in there that sends you email is because you'll end up on every spam list in the universe and most of the submissions you get will be from bots. Like 20+ a day, I'd guess.

**Comment by kwritenow** [comment]
The third option seems best, but before we jump to that, how bad is it to just put my phone number and/or email on the site for initial launch?

**Comment by evz** [comment]
That wouldn't be too bad for a while. We'd want to shift to something better pretty quickly before you start getting crawled. Oh, speaking of which, we should probably setup google analytics for this. I'll open an issue.

**Comment by kwritenow** [comment]
There is an issue for that already
